package com.bancosantander.reglasnegociotc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InputRegla1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer montoAcumulado;
	private java.lang.String pagoRecurrente;

	private java.lang.String tcDomiciliada;

	private java.lang.String asistentContratada;

	private java.lang.String nomina;
	public InputRegla1() {
	}

	public java.lang.Integer getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(java.lang.Integer montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public java.lang.String getPagoRecurrente() {
		return this.pagoRecurrente;
	}

	public void setPagoRecurrente(java.lang.String pagoRecurrente) {
		this.pagoRecurrente = pagoRecurrente;
	}

	public java.lang.String getTcDomiciliada() {
		return this.tcDomiciliada;
	}

	public void setTcDomiciliada(java.lang.String tcDomiciliada) {
		this.tcDomiciliada = tcDomiciliada;
	}

	public java.lang.String getAsistentContratada() {
		return this.asistentContratada;
	}

	public void setAsistentContratada(java.lang.String asistentContratada) {
		this.asistentContratada = asistentContratada;
	}

	public java.lang.String getNomina() {
		return this.nomina;
	}

	public void setNomina(java.lang.String nomina) {
		this.nomina = nomina;
	}

	public InputRegla1(java.lang.Integer montoAcumulado,
			java.lang.String pagoRecurrente, java.lang.String tcDomiciliada,
			java.lang.String asistentContratada, java.lang.String nomina) {
		this.montoAcumulado = montoAcumulado;
		this.pagoRecurrente = pagoRecurrente;
		this.tcDomiciliada = tcDomiciliada;
		this.asistentContratada = asistentContratada;
		this.nomina = nomina;
	}

}